const DATA=window.APP_DATA;
const $=s=>document.querySelector(s);
let program='all',query='',year='all',province='all',officer='all',progress='all';
const safe=v=>String(v??'—').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const pct=v=>`${Math.max(0,Math.min(100,Number(v||0))).toLocaleString('th-TH',{maximumFractionDigits:1})}%`;
const yearLabel=v=>Number(v)===1?'ปีที่ 1 (แปลงปี 66)':`ปีที่ ${v}`;
const latestNo=x=>x.latestWork?Number(String(x.latestWork.name).replace(/\D/g,''))||0:0;
function filtered(){return DATA.records.filter(x=>(program==='all'||x.program===program)&&(year==='all'||String(x.year)===year)&&(province==='all'||x.province===province)&&(officer==='all'||x.officer===officer)&&(progress==='all'||(progress==='complete'&&Number(x.completion)>=99.95)||(progress==='progress'&&Number(x.completion)>0&&Number(x.completion)<99.95)||(progress==='not-started'&&Number(x.completion)<=0))&&`${x.plot} ${x.province} ${x.district} ${x.contractor} ${x.officer} ${x.stcToRokContract} ${x.rokToContractorContract}`.toLowerCase().includes(query))}
function render(){const a=filtered();$('#count').textContent=`${a.length.toLocaleString('th-TH')} รายการ`;$('#list').innerHTML=a.length?a.map(x=>`<button class="card" data-id="${safe(x.id)}"><div><div><span class="tag">${safe(x.program)}</span> <span class="year">${yearLabel(x.year)}</span></div><h2>${safe(x.plot)}</h2><p>${safe([x.province,x.district].filter(Boolean).join(' • ')||'ไม่ระบุพื้นที่')}</p><div class="card-detail">ทั้งหมด ${Number(x.totalInstallments||0)} งวด · ${x.latestWork?`ถึงงวดที่ ${latestNo(x)}`:'ยังไม่เริ่มงวดงาน'}<br>เจ้าหน้าที่: ${safe(x.officer)}<br>ผรม.: ${safe(x.contractor)}</div></div><b>${pct(x.completion)}</b></button>`).join(''):'<p class="empty">ไม่พบแปลงที่ค้นหา</p>';document.querySelectorAll('.card').forEach(b=>b.onclick=()=>show(DATA.records.find(x=>x.id===b.dataset.id)))}
function planHtml(x){const tasks=Array.isArray(x.planTasks)?x.planTasks:[],dates=Array.isArray(x.planDates)?x.planDates:[],total=Number(x.totalInstallments||tasks.length||0),current=latestNo(x);if(!total)return '<p class="muted">ไม่พบรายละเอียดงวดงาน</p>';return Array.from({length:total},(_,i)=>{const n=i+1,items=tasks[i]||[],d=dates[i]||{};return `<div class="plan-item ${n<=current?'done':''}"><div class="plan-head"><b>งวดงานที่ ${n}</b><em>${n<=current?'ดำเนินการแล้ว':'รอดำเนินการ'}</em></div>${d.start||d.end?`<div class="plan-date">${safe(d.start||'ไม่ระบุ')} – ${safe(d.end||'ไม่ระบุ')}</div>`:''}${items.length?`<ul>${items.map(t=>`<li>${safe(t)}</li>`).join('')}</ul>`:'<small>ไม่พบหัวข้องานหลักในตารางแผน</small>'}</div>`}).join('')}
function show(x){if(!x)return;const latestWork=x.latestWork?`ดำเนินงานถึงงวดที่ ${latestNo(x)} จากทั้งหมด ${Number(x.totalInstallments||0)} งวด`:`ยังไม่เริ่มงวดงาน (ทั้งหมด ${Number(x.totalInstallments||0)} งวด)`;const latestPay=x.latestPayment?`${safe(x.latestPayment.name)} · ${pct(x.latestPayment.percent)}`:'ยังไม่พบรายการเบิกจ่าย';const period=x.contractPeriod||{};$('#detail').innerHTML=`<p class="kicker">${safe(x.program)} · ${yearLabel(x.year)}</p><h2 id="detail-title">${safe(x.plot)}</h2><p class="detail-meta">${safe([x.province,x.district].filter(Boolean).join(' • ')||'ไม่ระบุพื้นที่')}${x.status?` · ${safe(x.status)}`:''}</p><div class="latest work"><small>สถานะงวดงาน</small><strong>${latestWork}</strong></div>${x.planGroup?`<p class="plan-group">แผนกลุ่ม ${safe(x.planGroup)}</p>`:''}<h3 class="section-title">รายละเอียดงวดงานทั้งหมด</h3><div class="work-plan">${planHtml(x)}</div><div class="latest payment"><small>สถานะการจ่ายเงินงวดล่าสุด</small><strong>${latestPay}</strong></div><h3 class="section-title">ข้อมูลแปลง</h3><dl><dt>เนื้อที่</dt><dd>${x.area?Number(x.area).toLocaleString('th-TH',{maximumFractionDigits:2})+' ไร่':'—'}</dd><dt>ผู้รับเหมา</dt><dd>${safe(x.contractor)}</dd><dt>เจ้าหน้าที่</dt><dd>${safe(x.officer)}</dd><dt>STC to ROK</dt><dd>${safe(x.stcToRokContract)}</dd><dt>ROK–ผู้รับเหมา</dt><dd>${safe(x.rokToContractorContract)}</dd>${period.start||period.end?`<dt>ระยะเวลาสัญญา</dt><dd>${safe(period.start||'ไม่ระบุ')} – ${safe(period.end||'ไม่ระบุ')}</dd>`:''}${Array.isArray(x.kmzLinks)&&x.kmzLinks.length?`<dt>ไฟล์ KMZ</dt><dd>${x.kmzLinks.map(k=>safe(k.split('/').pop())).join('<br>')}</dd>`:''}</dl>`;$('#sheet').hidden=false;document.body.style.overflow='hidden'}
function close(){ $('#sheet').hidden=true;document.body.style.overflow='' }
$('#updated').textContent=DATA.updated;const prov=$('#province-filter'),off=$('#officer-filter');[...new Set(DATA.records.map(x=>x.province).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'th')).forEach(v=>prov.insertAdjacentHTML('beforeend',`<option value="${safe(v)}">${safe(v)}</option>`));[...new Set(DATA.records.map(x=>x.officer).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'th')).forEach(v=>off.insertAdjacentHTML('beforeend',`<option value="${safe(v)}">${safe(v)}</option>`));$('#search').oninput=e=>{query=e.target.value.trim().toLowerCase();render()};document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{program=b.dataset.program;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render()});$('#year-filter').onchange=e=>{year=e.target.value;render()};prov.onchange=e=>{province=e.target.value;render()};off.onchange=e=>{officer=e.target.value;render()};$('#progress-filter').onchange=e=>{progress=e.target.value;render()};$('#close').onclick=close;$('#sheet').onclick=e=>{if(e.target===$('#sheet'))close()};render();